//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class prenda
    {
        public int IdPrenda { get; set; }
        public string nombrePrenda { get; set; }
        public string cantidadPrenda { get; set; }
    }
}
