//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int IdUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string passUsuario { get; set; }
        public string rolUsuario { get; set; }
    }
}
