//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lavanderia
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int IdVenta { get; set; }
        public Nullable<int> cantidadCargaLigera { get; set; }
        public Nullable<double> totalCargaLigera { get; set; }
        public Nullable<int> cantidadCargaPesada { get; set; }
        public Nullable<double> totalCargaPesada { get; set; }
        public Nullable<int> cantidadPlanchado { get; set; }
        public Nullable<double> totalPlanchado { get; set; }
        public Nullable<double> totalVenta { get; set; }
    }
}
